/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author EZIO AUDITORY
 */
public class home extends javax.swing.JFrame {

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        studentManagerButton = new javax.swing.JButton();
        teacherManagerButton = new javax.swing.JButton();
        subjectManagerButton = new javax.swing.JButton();
        classManagerButton = new javax.swing.JButton();
        paymentManagerButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        FileMenu = new javax.swing.JMenu();
        EditMenu = new javax.swing.JMenu();
        MenusMenu = new javax.swing.JMenu();
        StudentManagerMenuItem = new javax.swing.JMenuItem();
        TeacherManagerMenuItem = new javax.swing.JMenuItem();
        SubjectManagerMenuItem = new javax.swing.JMenuItem();
        ClassManagerMenuItem = new javax.swing.JMenuItem();
        PaymentManagerMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Myriad Pro", 1, 48)); // NOI18N
        jLabel1.setText("ADYAPANA");
        jLabel1.setAutoscrolls(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Menus", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        studentManagerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        studentManagerButton.setText("Student Manager");
        studentManagerButton.setBorder(null);
        studentManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentManagerButtonActionPerformed(evt);
            }
        });

        teacherManagerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        teacherManagerButton.setText("Teacher Manager");
        teacherManagerButton.setBorder(null);
        teacherManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teacherManagerButtonActionPerformed(evt);
            }
        });

        subjectManagerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        subjectManagerButton.setText("Subject Manager");
        subjectManagerButton.setBorder(null);
        subjectManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectManagerButtonActionPerformed(evt);
            }
        });

        classManagerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        classManagerButton.setText("Class Manager");
        classManagerButton.setBorder(null);
        classManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                classManagerButtonActionPerformed(evt);
            }
        });

        paymentManagerButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        paymentManagerButton.setText("Payment Manager");
        paymentManagerButton.setBorder(null);
        paymentManagerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentManagerButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(paymentManagerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(studentManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(365, 365, 365)))
                    .addComponent(subjectManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teacherManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(teacherManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(paymentManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subjectManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(classManagerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Myriad Pro", 0, 18)); // NOI18N
        jLabel2.setText("AN INSTITUTE FOR STUDENTS WHO HAVE COMPLETED THEIR ADVANCED LEVELS IN THE SCIENCE STREAM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator1))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(435, 435, 435))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(159, 159, 159))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addGap(36, 36, 36)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        FileMenu.setText("File");
        jMenuBar1.add(FileMenu);

        EditMenu.setText("Edit");
        jMenuBar1.add(EditMenu);

        MenusMenu.setText("Menus");

        StudentManagerMenuItem.setText("Student Manager");
        StudentManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentManagerMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(StudentManagerMenuItem);

        TeacherManagerMenuItem.setText("Teacher Manager");
        TeacherManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TeacherManagerMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(TeacherManagerMenuItem);

        SubjectManagerMenuItem.setText("Subject Manager");
        SubjectManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubjectManagerMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(SubjectManagerMenuItem);

        ClassManagerMenuItem.setText("Class  Manager");
        ClassManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClassManagerMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(ClassManagerMenuItem);

        PaymentManagerMenuItem.setText("Payment Manager");
        PaymentManagerMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PaymentManagerMenuItemActionPerformed(evt);
            }
        });
        MenusMenu.add(PaymentManagerMenuItem);

        jMenuBar1.add(MenusMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentManagerButtonActionPerformed
        // TODO add your handling code here:
        new studentManager().setVisible(true);
    }//GEN-LAST:event_studentManagerButtonActionPerformed

    private void teacherManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teacherManagerButtonActionPerformed
        // TODO add your handling code here:
        new teacherManager().setVisible(true);
    }//GEN-LAST:event_teacherManagerButtonActionPerformed

    private void paymentManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentManagerButtonActionPerformed
        // TODO add your handling code here:
        new paymentManager().setVisible(true);
    }//GEN-LAST:event_paymentManagerButtonActionPerformed

    private void subjectManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectManagerButtonActionPerformed
        // TODO add your handling code here:
        new subjectManager().setVisible(true);
    }//GEN-LAST:event_subjectManagerButtonActionPerformed

    private void classManagerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_classManagerButtonActionPerformed
        // TODO add your handling code here:
        new classManager().setVisible(true);
    }//GEN-LAST:event_classManagerButtonActionPerformed

    private void StudentManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentManagerMenuItemActionPerformed
        // TODO add your handling code here:
        new studentManager().setVisible(true);
    }//GEN-LAST:event_StudentManagerMenuItemActionPerformed

    private void TeacherManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TeacherManagerMenuItemActionPerformed
        // TODO add your handling code here:
        new teacherManager().setVisible(true);
    }//GEN-LAST:event_TeacherManagerMenuItemActionPerformed

    private void SubjectManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubjectManagerMenuItemActionPerformed
        // TODO add your handling code here:
        new subjectManager().setVisible(true);
    }//GEN-LAST:event_SubjectManagerMenuItemActionPerformed

    private void ClassManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClassManagerMenuItemActionPerformed
        // TODO add your handling code here:
        new classManager().setVisible(true);
    }//GEN-LAST:event_ClassManagerMenuItemActionPerformed

    private void PaymentManagerMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PaymentManagerMenuItemActionPerformed
        // TODO add your handling code here:
        new paymentManager().setVisible(true);
    }//GEN-LAST:event_PaymentManagerMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClassManagerMenuItem;
    private javax.swing.JMenu EditMenu;
    private javax.swing.JMenu FileMenu;
    private javax.swing.JMenu MenusMenu;
    private javax.swing.JMenuItem PaymentManagerMenuItem;
    private javax.swing.JMenuItem StudentManagerMenuItem;
    private javax.swing.JMenuItem SubjectManagerMenuItem;
    private javax.swing.JMenuItem TeacherManagerMenuItem;
    private javax.swing.JButton classManagerButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton paymentManagerButton;
    private javax.swing.JButton studentManagerButton;
    private javax.swing.JButton subjectManagerButton;
    private javax.swing.JButton teacherManagerButton;
    // End of variables declaration//GEN-END:variables
}
